// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0SX0hPK5AB5V6RnEyydHkg6q3NWzydqc',
    appId: '1:435952358500:android:a5daaef9bed9366095bb71',
    messagingSenderId: '435952358500',
    projectId: 'legacy-8a4b3',
    storageBucket: 'legacy-8a4b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4j8s0D9c4l6Kec1yOOb4QKyxhGhqXTLA',
    appId: '1:435952358500:ios:6190e058680d7b1d95bb71',
    messagingSenderId: '435952358500',
    projectId: 'legacy-8a4b3',
    storageBucket: 'legacy-8a4b3.firebasestorage.app',
    iosBundleId: 'com.example.secureLegacyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4j8s0D9c4l6Kec1yOOb4QKyxhGhqXTLA',
    appId: '1:435952358500:ios:6190e058680d7b1d95bb71',
    messagingSenderId: '435952358500',
    projectId: 'legacy-8a4b3',
    storageBucket: 'legacy-8a4b3.firebasestorage.app',
    iosBundleId: 'com.example.secureLegacyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB377L-QbNjIXoEoRLbuRSYbe99BIIiCDs',
    appId: '1:435952358500:web:50b76dd3317d224995bb71',
    messagingSenderId: '435952358500',
    projectId: 'legacy-8a4b3',
    authDomain: 'legacy-8a4b3.firebaseapp.com',
    storageBucket: 'legacy-8a4b3.firebasestorage.app',
    measurementId: 'G-H6JBVP8X9S',
  );
}
